spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/workspace-ecommerce/H2/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
